# Generated by Django 3.0.5 on 2020-09-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_confirmation_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeUser',
        ),
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
