# Generated by Django 3.0.5 on 2020-09-30 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_auto_20200930_1853"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Review",
                to="api.Titles",
            ),
            preserve_default=False,
        ),
    ]
