# Generated by Django 3.0.5 on 2020-10-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_titles_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='rating',
        ),
    ]
