# Generated by Django 3.0.5 on 2020-10-04 18:47

import django.core.validators
from django.db import migrations, models

import api.utils


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20201004_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(default='2020', validators=[django.core.validators.MinValueValidator(1700), api.utils.max_value_current_year]),
        ),
    ]
